services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=mysql
      - MONGO_HOST=mongodb
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Lshdgsw71
      MYSQL_DATABASE: chatprac
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  mongodb:
    image: mongo:8
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Lshdgsw71
      MONGO_INITDB_DATABASE: chat
    ports:
      - "27016:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mysql-data:
  mongodb-data:

networks:
  app-network:
    driver: bridge