services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=mysql
      - MONGO_HOST=mongodb
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Lshdgsw71
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  mongodb:
    image: mongo:8
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    ports:
      - "27016:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mysql-data:
  mongodb-data:

networks:
  app-network:
    driver: bridge