server:
  port: 8080

# MySQL Info 본인 MySQL로 수정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatprac
    username: root
    password: Lshdgsw71
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat

    redis:
      host: localhost
      port: 6379
      password: Lshdgsw71
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: leegeh1213@gmail.com
    password: "ueda nakv ykhn bwvj"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
      auth-code-expiration-millis: 1800000

# logging
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            mongodb: debug      # Spring Data MongoDB의 로그를 debug 레벨로 설정
      mongodb:
        driver: debug          # MongoDB 드라이버 관련 로그를 debug 레벨로 설정
#    root: debug
#JWT Secret Random code (32바이트 길이의 무작위 바이트 문자열을 64자 길이의 16진수 문자열로 인코딩)
jwt :
  secret : 4626379cadc10451644ebfc33bdef68993cd3edc426640f8c28758cd853dbfa5
  expire :
    #access: 600000 = 2 hour
    access: 6000000
    #refresh: 864000000 = 10 day
    refresh: 864000000